// S9d: multi-frame scoring + assembler-chain probes. Synthetic local fixture only.
import fs from 'node:fs';
const PORT=process.env.CDP_PORT||'9226', OUT=process.env.OUT||'/tmp/zai-recon-5';
fs.mkdirSync(OUT,{recursive:true}); const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const tabs=(await (await fetch(`http://127.0.0.1:${PORT}/json/list`)).json()).filter(x=>x.type==='page');
let tab=tabs.find(x=>/chat\.z\.ai/.test(x.url||''))||tabs[0]; if(!tab)throw Error('no page');
async function open(t){const w=new WebSocket(t.webSocketDebuggerUrl);await new Promise(r=>w.onopen=r);let id=0;const p=new Map(),events=[];w.onmessage=e=>{const m=JSON.parse(e.data);if(m.id&&p.has(m.id)){p.get(m.id)(m);p.delete(m.id)}else if(m.method)events.push(m)};const send=(m,pa={},to=30000)=>new Promise(r=>{const i=++id,tm=setTimeout(()=>{p.delete(i);r({timeout:true})},to);p.set(i,x=>{clearTimeout(tm);r(x)});w.send(JSON.stringify({id:i,method:m,params:pa}))});return {w,send,events,ev:async e=>(await send('Runtime.evaluate',{expression:e,returnByValue:true}))?.result?.result?.value}}
// Prefer the page carrying the 4-in-1 fixture hooks.
for(const t of tabs.filter(x=>x.type==='page')){try{const q=await open(t);const yes=await q.ev('!!window.__R4');if(yes){tab=t;q.w.close();break}q.w.close()}catch{}}
const C=await open(tab),send=C.send,ev=C.ev,w=C.w,events=C.events;
await send('Page.bringToFront');await send('Emulation.setFocusEmulationEnabled',{enabled:true});await send('Debugger.enable');await sleep(1200);
const scripts=events.filter(x=>x.method==='Debugger.scriptParsed').map(x=>x.params);
const pe=[...scripts].reverse().find(p=>/dynamicJS.*pe\./.test(String(p.url||'')));if(!pe){console.log('NO_PE');process.exitCode=10;w.close();}
const src=(await send('Debugger.getScriptSource',{scriptId:pe.scriptId},30000))?.result?.scriptSource||'';
const raw=[];let m;const rx=/=JSON\[[^\]]{1,70}\(/g;while((m=rx.exec(src))&&raw.length<48)raw.push(m.index);
const cols=[...new Set(raw.flatMap(p=>[p-30,p-20,p-13,p,p+5,p+13,p+22].filter(x=>x>0)))];const bps=[];
for(const columnNumber of cols){const r=await send('Debugger.setBreakpoint',{location:{scriptId:pe.scriptId,lineNumber:0,columnNumber}});if(r?.result?.breakpointId)bps.push({bid:r.result.breakpointId,requested:columnNumber,actual:r.result.actualLocation?.columnNumber??null})}
const log=s=>{console.log(s);fs.appendFileSync(`${OUT}/s9d.log`,s+'\n')};log(`[P1] pe=${pe.url} source=${src.length} raw=${raw.length} bps=${bps.length} tab=${tab.url}`);
await ev(`(()=>{for(const id of ['aliyunCaptcha-window-popup','aliyunCaptcha-mask']){const e=document.getElementById(id);if(e)e.style.display='block'}return 1})()`);await sleep(500);
const slider=JSON.parse(await ev(`(()=>{const e=document.getElementById('aliyunCaptcha-sliding-slider');if(!e)return '{}';const r=e.getBoundingClientRect();return JSON.stringify({x:r.x+r.width/2,y:r.y+r.height/2})})()`));
if(!slider.x){log('NO_SLIDER');process.exitCode=11;w.close();}
await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:slider.x,y:slider.y});await send('Input.dispatchMouseEvent',{type:'mousePressed',x:slider.x,y:slider.y,button:'left',clickCount:1});const steps=30;
for(let i=1;i<=steps;i++){const k=i/steps,e=k<.5?2*k*k:1-Math.pow(-2*k+2,2)/2;await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:slider.x+250*e,y:slider.y+(Math.random()-.5)*2,button:'left'});await sleep(16)}
await send('Input.dispatchMouseEvent',{type:'mouseReleased',x:slider.x+250,y:slider.y,button:'left',clickCount:1});log('[P2] drag released');
let pause,last=0;const until=Date.now()+110000;while(Date.now()<until){const a=events.filter(x=>x.method==='Debugger.paused');if(a.length>last){pause=a[a.length-1];last=a.length;if(last>=3||await ev('!!(window.__CVPS&&window.__CVPS.length)'))break}await sleep(100)}
if(!pause){log('[P3] NO_PAUSE');for(const b of bps)await send('Debugger.removeBreakpoint',{breakpointId:b.bid});w.close();process.exitCode=12}
const frameEval=async(f,e,to=18000)=>{const r=await send('Debugger.evaluateOnCallFrame',{callFrameId:f.callFrameId,expression:e,returnByValue:true,awaitPromise:true},to);return r?.result?.exceptionDetails?{error:String(r.result.exceptionDetails.text||r.result.exceptionDetails.description||'').slice(0,400)}:{value:r?.result?.result?.value}};
const frames=pause.params.callFrames||[];const report={generatedAt:new Date().toISOString(),pe:pe.url,hit:frames[0]?.location||null,frames:[],probes:[],cvpsBefore:await ev('JSON.stringify(window.__CVPS||[])')};
for(let fi=0;fi<Math.min(frames.length,24);fi++){const f=frames[fi],names=new Set();for(const sc of f.scopeChain||[]){if(!sc.object?.objectId)continue;const q=await send('Runtime.getProperties',{objectId:sc.object.objectId,ownProperties:true});for(const x of q?.result?.result||[])if(!['this','arguments'].includes(x.name))names.add(x.name)}const q=await frameEval(f,`(function(){const ns=${JSON.stringify([...names])},o={frame:${fi},names:ns,values:[],functions:[],materials:[],cvps:[]};for(const n of ns){let v;try{v=eval(n)}catch(_){continue}if(v==null)continue;try{if(typeof v==='string')o.values.push({name:n,type:'string',len:v.length,head:v.slice(0,80)});else if(typeof v==='function'){let s=String(v);o.functions.push({name:n,len:s.length,head:s.slice(0,300)})}else if(typeof v==='object'){let ks=Object.keys(v),j=null;try{j=JSON.stringify(v).slice(0,10000)}catch(_){}o.values.push({name:n,type:'object',keys:ks.slice(0,120),json:j});if(ks.includes('TrackList')||ks.includes('TrackStartTime'))o.materials.push(n);if(ks.includes('certifyId')||ks.includes('deviceToken')||ks.includes('data'))o.cvps.push(n)}}catch(e){}}return JSON.stringify(o)})()`);let d;try{d=JSON.parse(q.value||'{}')}catch{d={frame:fi,parseError:q.value||q.error}}report.frames.push(d)}
function score(d){return (d.materials?.length?100000:0)+(d.cvps?.length?10000:0)+(d.functions||[]).reduce((a,x)=>a+Math.min(x.len,50000),0)+((d.functions||[]).some(x=>x.len>8000)?5000:0)}
const elig=report.frames.map((d,i)=>({i,d,s:score(d)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s).slice(0,4);log(`[P3] frames=${frames.length} eligible=${elig.map(x=>`${x.i}:${x.s}`).join(',')}`);
for(const pick of elig){const f=frames[pick.i],d=pick.d,mat=d.materials?.[0]||d.values?.find(x=>x.type==='object'&&/TrackList|TrackStartTime/.test(x.json||''))?.name||'undefined',cvp=d.cvps?.[0]||'undefined';const fn=[...new Set(['th','tu','ts','np','nh','e','s','tl','tc',...(d.functions||[]).filter(x=>x.len>8000).map(x=>x.name)])];
const variants={mat:`${mat}`,mat_json:`JSON.stringify(${mat})`,cvp:`${cvp}`,mat_cvp:`${mat},${cvp}`,mat_data:`${mat},${cvp}&&${cvp}.data`};
const test=async(label,expr)=>{const q=await frameEval(f,`(function(){try{const z=(${expr});return JSON.stringify({ok:1,type:typeof z,len:z&&z.length||null,head:String(z??'').slice(0,60)})}catch(e){return JSON.stringify({ok:0,error:String(e).slice(0,220)})}})()`);let r;try{r=JSON.parse(q.value||'{}')}catch{r={raw:q.value||q.error}}report.probes.push({frame:pick.i,kind:label,result:r})};
for(const name of fn)for(const [v,a] of Object.entries(variants))for(const op of Array.from({length:32},(_,i)=>i))await test(`${name} op=${op} ${v}`,`typeof ${name}==='function'?${name}.call(this,${op},${a}):undefined`);
const chains={ts11:`typeof ts==='function'?ts.call(this,11,${mat}):undefined`,np:`typeof np==='function'?np.call(this,${mat}):undefined`,iife_np:`typeof nh==='function'&&typeof np==='function'?(()=>{const z=nh(${mat});return np(z)})():undefined`,th11:`typeof th==='function'?th.call(this,11,${mat}):undefined`,chain_full:`typeof nh==='function'&&typeof np==='function'&&typeof ts==='function'?(()=>{const z=nh(${mat});const y=np(z);return ts.call(this,11,y)})():undefined`};for(const [k,e] of Object.entries(chains))await test(`CHAIN ${k}`,e)}
report.cvpsAfter=await ev('JSON.stringify(window.__CVPS||[])');report.hits=report.probes.filter(x=>x.result?.head?.startsWith('JRM')||(x.result?.len>=700&&x.result?.len<=800));
const file=`${OUT}/s9d-${Date.now()}.json`;fs.writeFileSync(file,JSON.stringify(report,null,2));fs.writeFileSync(`${OUT}/S9-LAST.json`,JSON.stringify(report,null,2));log(`[P5] wrote ${file} probes=${report.probes.length} hits=${report.hits.length}`);for(const b of bps)if(b.bid)await send('Debugger.removeBreakpoint',{breakpointId:b.bid});await send('Debugger.resume');await send('Debugger.disable');w.close();